+ Request (application/json)
    + Attributes (AuthorRequest)
    + Headers
         ```
         X-Authorization: <your-api-key>
         Accept: application/json
         ```
    + Body
        ```json
        {
            "last_name": "Rau",
            "first_name": "Gage",
            "date_of_birth": "2011-10-30 00:00:00",
            "homepage": "http://www.lowe.biz/fugiat-doloribus-in-beatae-aut-alias",
            "country_code": "US"
        }
        ```
    + Schema
        ```json
        :[](../../schemas/authors-store.json)
        ```
