+ Request (application/json)
    + Attributes (BookRequest)
    + Headers
         ```
         X-Authorization: <your-api-key>
         Accept: application/json
         ```
    + Body
        ```json
        {
            "id": 25,
            "title": "maxime sint voluptates",
            "description": "Et qui ab odit hic nemo illum. Sint velit adipisci qui mollitia est. Qui vel qui dignissimos qui.",
            "publisher": "sint",
            "price": 15,
            "author_id": 16,
            "country_code": "CH",
            "language_code": "fr"
        }
        ```
