+ Request (application/json)
    + Headers
        ```
        X-Authorization: <your-api-key>
        Accept: application/json
        ```
    + Body
        ```json
        {
            "code": "DE",
            "name": "Germany"
        }
        ```
    + Schema
        ```json
        :[](../../schemas/countries-store.json)
        ``` 
