+ Request (application/json)
    + Headers
        ```
        X-Authorization: <your-api-key>
        ```
        + Body
            ```json
            {
                "code": "de",
                "name": "German"
            }
            ```
        + Schema
            ```json
            :[](../../schemas/languages-store.json)
            ``` 
