[adapters.api-blueprint]
ungroup_root = true

[plugins.postman]
output = "exports/postman"
group_by = "trie"

[plugins.json-schemas]
output = "exports/schemas"

[plugins.documentation]
output = "docs/"
group_by = "trie"
flatten = true
  [plugins.documentation.data]
  title = "Travel Books API"
